version: "3"

services:
  db:
    container_name: dog_adoption_db
    image: postgres
    volumes:
      - dog_adoption_data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  backend:
    container_name: dog_adoption_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/dog_adoption:/dog_adoption
      - dog_adoption_data_volume:/dog_adoption/staticfiles
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=dog_adoption.settings_dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db

  frontend:
    container_name: dog_adoption_front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dog_adoption:/dog_adoption
    tty: true
    command: sh -c "yarn start"
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - backend

  nginx:
    container_name: dog_adoption_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend

volumes:
  dog_adoption_data_volume:
